In [1]:
d1<-read.csv("c1.csv")

In [2]:
d1

    Shoe Height Count
1   4.0  60.0   0
2   4.5  60.0   0
3   5.0  59.0   0
4   5.0  59.0   1
5   5.0  60.0   0
6   5.0  60.0   1
7   5.0  60.0   2
8   5.0  60.0   3
9   5.0  62.0   0
10  5.0  64.0   0
11  5.5  61.0   0
12  5.5  61.0   1
13  5.5  62.0   0
14  6.0  61.0   0
15  6.0  62.0   0
16  6.0  62.0   1
17  6.0  62.0   2
18  6.0  63.0   0
19  6.0  64.0   0
20  6.0  64.0   1
21  6.0  65.0   0
22  6.5  61.0   0
23  6.5  62.0   0
24  6.5  62.0   1
25  6.5  62.5   0
26  6.5  63.0   0
27  6.5  63.0   1
28  6.5  65.0   0
29  7.0  58.0   0
30  7.0  59.0   0
⋮   ⋮    ⋮      ⋮
196 11.0 73.0   1
197 11.0 74.0   0
198 11.0 76.0   0
199 11.0 77.0   0
200 11.5 69.5   0
201 11.5 71.0   0
202 11.5 71.0   1
203 11.5 71.0   2
204 11.5 71.0   3
205 11.5 75.0   0
206 11.5 76.0   0
207 12.0 72.0   0
208 12.0 72.0   1
209 12.0 72.0   2
210 12.0 73.0   0
211 12.0 73.0   1
212 12.0 73.0   2
213 12.0 78.0   0
214 13.0 68.0   0
215 13.0 70.0   0
216 13.0 71.0   0
217 13.0 72.0   0
218 13.0 73.0   0
219 13.0 73.0   1
220 13.0 73.0   2
221 13.0 74.0   0
222 13.0 75.0   0
223 13.0 75.0   1
224 14.0 70.0   0
225 15.0 76.0   0

In [ ]:
install.packages("plotly")

Installing package into ‘/srv/rlibs’
(as ‘lib’ is unspecified)

In [ ]:
library("plotly")
fig<- plot_ly(d1, x=~Shoe, y=~Height, z=~Count, type="scatter3d", mode="markers")
fig <- fig %>% layout(scene=list(aspectmode="manual", aspectratio=list(x=3,y=1,z=1)))
fig